import "./globals.css";
import { Montserrat } from "next/font/google";
/** Component */
import { Navbar, Footer } from "@/components";
/** Next Image */
import Image, { StaticImageData } from "next/image";
/** Image */
import WAIcon from "@/assets/whatsapp-icon.png";

const monsetrrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Alya Esthetic Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${monsetrrat.className}`}>
        <Navbar />
        <Image
          src={WAIcon}
          alt="Whatsapp Alya Esthetic"
          className="fixed bottom-[40px] right-[40px] z-10 cursor-pointer"
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
